name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-contracts:
    name: Testar Contratos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Instalar Dependências
        run: |
          npm ci
          cd contracts && npm ci
          
      - name: Verificar Formatação
        run: |
          npm run lint
          cd contracts && npm run lint
          
      - name: Testar Contratos
        run: |
          cd contracts
          npm run test
          
      - name: Verificar Cobertura de Testes
        run: |
          cd contracts
          npm run coverage

  test-frontend:
    name: Testar Frontend
    runs-on: ubuntu-latest
    needs: test-contracts
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Instalar Dependências
        run: npm ci
        
      - name: Verificar Formatação
        run: npm run lint
        
      - name: Testar Frontend
        run: npm run test
        
      - name: Verificar Build
        run: npm run build

  security:
    name: Verificar Segurança
    runs-on: ubuntu-latest
    needs: [test-contracts, test-frontend]
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Instalar Dependências
        run: npm ci
        
      - name: Verificar Vulnerabilidades
        run: |
          npm audit
          cd contracts && npm audit
          
      - name: Verificar Segurança do Código
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          
      - name: Verificar Segurança dos Contratos
        run: cd contracts && snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [test-contracts, test-frontend, security]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Instalar Dependências
        run: npm ci
        
      - name: Deploy Contratos
        run: |
          cd contracts
          npm run deploy:${{ secrets.NETWORK }}
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          
      - name: Deploy Frontend
        run: npm run deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} 